# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import exos_test.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2017, 2, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.PositiveSmallIntegerField(default=exos_test.apps.users.models.get_random),
        ),
    ]
